import PDFDocument from "pdfkit";

const LIME = "#5b8a00";
const INK = "#111318";
const GRAY = "#6b7280";

function drawReport(doc, lead) {
  // header
  doc.rect(0, 0, doc.page.width, 90).fill("#0a0a0b");
  doc.fillColor("#c2f54b").fontSize(20).font("Helvetica-Bold").text("FORWARDLY", 48, 30);
  doc.fillColor("#9ca3af").fontSize(9).font("Helvetica").text("Lead Pitch & Research Report", 48, 56);
  doc.fillColor("#c2f54b").fontSize(9).text(new Date().toDateString(), 0, 34, { align: "right", width: doc.page.width - 48 });

  let y = 120;
  doc.fillColor(INK).fontSize(22).font("Helvetica-Bold").text(lead.name, 48, y);
  y = doc.y + 6;
  doc.fillColor(GRAY).fontSize(10).font("Helvetica").text(
    `${lead.industry || "Business"}  ·  ${[lead.city, lead.pincode].filter(Boolean).join(" ")}`,
    48, y
  );

  y = doc.y + 10;
  const badge = (lead.classification || "hot").toUpperCase();
  doc.roundedRect(48, y, 60, 20, 10).fill(lead.classification === "hot" ? LIME : "#9ca3af");
  doc.fillColor("#ffffff").fontSize(10).font("Helvetica-Bold").text(badge, 48, y + 5, { width: 60, align: "center" });

  y += 40;
  doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text("Contact", 48, y);
  const line = (label, val) => {
    doc.fillColor(GRAY).fontSize(10).font("Helvetica-Bold").text(label, 48, doc.y, { continued: true });
    doc.fillColor(INK).font("Helvetica").text("  " + (val || "—"));
  };
  line("Phone:", lead.phone);
  line("Website:", lead.website || "None (opportunity)");
  line("Address:", lead.address);
  line("Google:", `${lead.rating || "—"}★  ·  ${lead.reviews || 0} reviews`);

  y = doc.y + 16;
  doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text("Summary", 48, y);
  doc.fillColor("#374151").fontSize(10).font("Helvetica").text(lead.research?.summary || "", 48, doc.y + 4, { width: doc.page.width - 96 });

  if (lead.research?.painPoints?.length) {
    doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text("Why they need us", 48, doc.y + 14);
    doc.moveDown(0.3);
    lead.research.painPoints.forEach((p) => {
      doc.fillColor(LIME).font("Helvetica-Bold").fontSize(10).text("•  ", { continued: true });
      doc.fillColor("#374151").font("Helvetica").text(p);
    });
  }

  doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text("Call pitch (mystery-shopper)", 48, doc.y + 14);
  doc.fillColor("#374151").fontSize(10).font("Helvetica").text(lead.research?.pitch || "", 48, doc.y + 4, {
    width: doc.page.width - 96, lineGap: 3,
  });

  doc.fillColor(GRAY).fontSize(8).text("Confidential · Generated by Forwardly Leads", 48, doc.page.height - 60, {
    align: "center", width: doc.page.width - 96,
  });
}

/** Stream a freshly-generated PDF to an Express response (no disk needed). */
export function streamReport(lead, res) {
  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const safe = (lead.name || "lead").replace(/[^\w-]/g, "_").slice(0, 40);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="Forwardly-${safe}.pdf"`);
  doc.pipe(res);
  drawReport(doc, lead);
  doc.end();
}
