import PDFDocument from "pdfkit";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FONT_HI = path.join(__dirname, "../assets/fonts/NotoSansDevanagari-Regular.ttf");
const FONT_HI_BOLD = path.join(__dirname, "../assets/fonts/NotoSansDevanagari-Bold.ttf");

const LIME = "#5b8a00";
const LIME_BRIGHT = "#c2f54b";
const INK = "#111318";
const BODY = "#2c313a";
const GRAY = "#6b7280";
const RULE = "#e6e8ec";
const M = 48; // page margin

/* ---- shared helpers ---- */
function sectionHead(doc, title) {
  doc.moveDown(0.7);
  doc.fillColor(LIME).font("Helvetica-Bold").fontSize(10.5).text(title.toUpperCase(), { characterSpacing: 0.6 });
  const ry = doc.y + 2.5;
  doc.moveTo(M, ry).lineTo(doc.page.width - M, ry).lineWidth(0.6).strokeColor(RULE).stroke();
  doc.moveDown(0.55);
}

/* Renders a pitch string: blocks separated by blank lines, first line of each
   block is the section header, the rest are body lines (bullets / [notes] / text). */
function drawPitch(doc, text) {
  const blocks = (text || "")
    .split(/\n\n+/)
    .map((b) => b.split("\n").filter((l) => l.length))
    .filter((a) => a.length);

  blocks.forEach(([head, ...body], idx) => {
    if (idx) doc.moveDown(0.85);

    // header — main part bold lime, parenthetical in gray
    const m = head.match(/^([^(]+?)(\s*\(.*\))?$/);
    const main = (m ? m[1] : head).trim();
    const paren = m && m[2] ? m[2] : "";
    doc.font("Helvetica-Bold").fontSize(10.5).fillColor(LIME).text(main, { continued: !!paren, characterSpacing: 0.4 });
    if (paren) doc.font("Helvetica").fillColor(GRAY).fontSize(9).text(paren, { characterSpacing: 0 });
    const ry = doc.y + 2.5;
    doc.moveTo(M, ry).lineTo(doc.page.width - M, ry).lineWidth(0.5).strokeColor(RULE).stroke();
    doc.moveDown(0.45);

    body.forEach((ln) => {
      if (/^•/.test(ln)) {
        doc.font("Helvetica-Bold").fontSize(10).fillColor(LIME).text("•  ", { continued: true });
        doc.font("Helvetica").fillColor(BODY).text(ln.replace(/^•\s*/, ""), { lineGap: 2.5 });
      } else if (/^\[/.test(ln)) {
        doc.font("Helvetica-Oblique").fontSize(9).fillColor(GRAY).text(ln, { lineGap: 2 });
      } else {
        doc.font("Helvetica").fontSize(10).fillColor(BODY).text(ln, { lineGap: 2.5 });
      }
      doc.moveDown(0.12);
    });
  });
}

function pageTitle(doc, kicker, title) {
  doc.fillColor(LIME).font("Helvetica-Bold").fontSize(9).text(kicker.toUpperCase(), M, 54, { characterSpacing: 1 });
  doc.fillColor(INK).font("Helvetica-Bold").fontSize(19).text(title, M, doc.y + 2);
  const ry = doc.y + 6;
  doc.moveTo(M, ry).lineTo(doc.page.width - M, ry).lineWidth(2).strokeColor(LIME_BRIGHT).stroke();
  doc.moveDown(1.1);
}

function footer(doc) {
  // draw in the bottom margin without triggering an auto page-break (recursion)
  const b = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;
  doc.fillColor("#9aa0aa").font("Helvetica").fontSize(8).text(
    "Confidential · Generated by Forwardly Leads",
    M, doc.page.height - 34, { align: "center", width: doc.page.width - 2 * M, lineBreak: false }
  );
  doc.page.margins.bottom = b;
}

function drawReport(doc, lead) {
  doc.registerFont("Devanagari", FONT_HI);
  doc.registerFont("Devanagari-Bold", FONT_HI_BOLD);
  const W = doc.page.width;

  /* ---------- page 1: profile ---------- */
  doc.rect(0, 0, W, 92).fill("#0a0a0b");
  doc.roundedRect(M, 30, 30, 30, 8).fill(LIME_BRIGHT);
  doc.fillColor("#0a0a0b").font("Helvetica-Bold").fontSize(19).text("F", M, 37, { width: 30, align: "center" });
  doc.fillColor("#ffffff").fontSize(17).font("Helvetica-Bold").text("FORWARDLY", M + 40, 34);
  doc.fillColor("#9ca3af").fontSize(9).font("Helvetica").text("Lead Pitch & Research Report", M + 40, 56);
  doc.fillColor(LIME_BRIGHT).fontSize(9).font("Helvetica").text(new Date().toDateString(), 0, 40, { align: "right", width: W - M });

  doc.fillColor(INK).fontSize(21).font("Helvetica-Bold").text(lead.name, M, 116, { width: W - 2 * M });
  doc.fillColor(GRAY).fontSize(10).font("Helvetica").text(
    `${lead.industry || "Business"}   ·   ${[lead.city, lead.pincode].filter(Boolean).join(" ")}`,
    M, doc.y + 5
  );

  // classification pill
  const badge = (lead.classification || "hot").toUpperCase();
  const py = doc.y + 10;
  const pw = 30 + doc.widthOfString(badge, { font: "Helvetica-Bold" });
  doc.roundedRect(M, py, pw, 21, 10.5).fill(lead.classification === "hot" ? LIME : "#9ca3af");
  doc.fillColor("#ffffff").fontSize(9.5).font("Helvetica-Bold").text(badge, M, py + 6, { width: pw, align: "center", characterSpacing: 0.5 });
  doc.y = py + 21;

  sectionHead(doc, "Contact");
  const line = (label, val) => {
    doc.fillColor(GRAY).fontSize(10).font("Helvetica-Bold").text(label + "  ", { continued: true });
    doc.fillColor(INK).font("Helvetica").text(val || "—");
    doc.moveDown(0.15);
  };
  line("Phone", lead.phone);
  line("Website", lead.website || "None (opportunity)");
  line("Address", lead.address);
  line("Google", `${lead.rating || "—"}/5   ·   ${lead.reviews || 0} reviews`);

  sectionHead(doc, "Summary");
  doc.fillColor(BODY).fontSize(10).font("Helvetica").text(lead.research?.summary || "—", { lineGap: 2.5, width: W - 2 * M });

  if (lead.research?.painPoints?.length) {
    sectionHead(doc, "Why they need us");
    lead.research.painPoints.forEach((p) => {
      doc.fillColor(LIME).font("Helvetica-Bold").fontSize(10).text("•  ", { continued: true });
      doc.fillColor(BODY).font("Helvetica").text(p, { lineGap: 2.5 });
      doc.moveDown(0.15);
    });
  }

  /* ---------- page 2: English pitch ---------- */
  doc.addPage();
  pageTitle(doc, "Call pitch", "English — mystery-shopper");
  drawPitch(doc, lead.research?.pitch || "Not generated yet.");

  /* ---------- page 3: Hinglish pitch ---------- */
  doc.addPage();
  pageTitle(doc, "Call pitch", "Hinglish — mystery-shopper");
  drawPitch(doc, lead.research?.pitchHi || "Hinglish script not generated yet — click Regenerate.");
}

/** Stream a freshly-generated PDF to an Express response (no disk needed). */
export function streamReport(lead, res) {
  const doc = new PDFDocument({ size: "A4", margin: M, bufferPages: true });
  const safe = (lead.name || "lead").replace(/[^\w-]/g, "_").slice(0, 40);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="Forwardly-${safe}.pdf"`);
  doc.pipe(res);
  drawReport(doc, lead);
  // stamp the footer on every page once, without disturbing content flow
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    footer(doc);
  }
  doc.flushPages();
  doc.end();
}
