// Shape of GET member-api/v2/home?uuId=... (confirmed live, flat — no
// {value: X} wrapping, unlike /core-api/profile which is a different,
// self-only endpoint):
// {
//   displayName, firstName, lastName, roleInfo, phoneNumber, mobileNumber,
//   emailAddress, websiteUrl, primaryCategory, secondaryCategory,
//   requiredSpeciality, companyName, business, keywords, memberChapter,
//   memberChapterId, mspStatus, ownProfile, ...
// }

export const CSV_COLUMNS = [
  "industry_keyword",
  "search_rank",
  "search_score",
  "search_company_name",
  "search_city",
  "search_state",
  "search_category",
  "search_speciality",
  "search_chapter_id",
  "search_membership_status",
  "user_id",
  "uuid",
  "display_name",
  "first_name",
  "last_name",
  "role_info",
  "phone_number",
  "mobile_number",
  "email_address",
  "website_url",
  "primary_category",
  "secondary_category",
  "required_speciality",
  "company_name",
  "business",
  "keywords",
  "address_line1",
  "address_line2",
  "city",
  "state",
  "country",
  "postcode",
  "member_chapter",
  "member_chapter_id",
  "msp_status",
  "contact_available",
  "raw_profile_json",
];

export function buildRow({ industry, searchResult, uuId, profile }) {
  const p = profile || {};
  const address = p.address || {};
  const phone = p.phoneNumber ?? "";
  const email = p.emailAddress ?? "";

  return {
    industry_keyword: industry,
    search_rank: searchResult.rank ?? "",
    search_score: searchResult.score ?? "",
    search_company_name: searchResult.company_name ?? "",
    search_city: searchResult.city ?? "",
    search_state: searchResult.state ?? "",
    search_category: searchResult.category ?? "",
    search_speciality: searchResult.speciality ?? "",
    search_chapter_id: searchResult.chapter_id ?? "",
    search_membership_status: searchResult.membership_status ?? "",
    user_id: searchResult.user_id ?? "",
    uuid: uuId ?? "",
    display_name: p.displayName ?? "",
    first_name: p.firstName ?? "",
    last_name: p.lastName ?? "",
    role_info: p.roleInfo ?? "",
    phone_number: phone,
    mobile_number: p.mobileNumber ?? "",
    email_address: email,
    website_url: p.websiteUrl ?? "",
    primary_category: p.primaryCategory ?? "",
    secondary_category: p.secondaryCategory ?? "",
    required_speciality: p.requiredSpeciality ?? "",
    company_name: p.companyName ?? "",
    business: p.business ?? "",
    keywords: p.keywords ?? "",
    address_line1: address.addressLine1 ?? "",
    address_line2: address.addressLine2 ?? "",
    city: address.city ?? "",
    state: address.state ?? "",
    country: address.countryName ?? address.country ?? "",
    postcode: address.postcode ?? "",
    member_chapter: p.memberChapter ?? "",
    member_chapter_id: p.memberChapterId ?? "",
    msp_status: p.mspStatus ?? "",
    contact_available: Boolean(phone || email),
    raw_profile_json: JSON.stringify(p),
  };
}
